[package]
name = "wasm-pages-test"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.11", default-features = false, features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "=0.2.117"
wasm-bindgen-futures = "0.4.54"
web-sys = { version = "0.3.82", features = ["Document", "Element", "HtmlElement", "Window"] }
gloo-net = { version = "0.6.0", default-features = false, features = ["http"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
